//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListItem()
        {
            this.ItemDetails = new HashSet<ItemDetail>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public long Id { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public string Phone { get; set; }
        public string Rating { get; set; }
        public string Address { get; set; }
        public string LogoImage { get; set; }
        public string BgImage { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastEdit { get; set; }
        public System.Data.Entity.Spatial.DbGeography Cords { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemDetail> ItemDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
