//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public string Status { get; set; }
        public string MovedBy { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
